### ISSUE TITLE
Open to changing crate name?

### ISSUE THREAD

**Issue by kvnvelasco** [mocsy/igraph#1]
Hello! 

I was wondering if you'd be open to changing the name of this crate on crates.io. I'm working on writing an interface to the igraph project (https://igraph.org/).

There is a sys-crate in development here https://docs.rs/igraph-sys/latest/igraph_sys that will be wrapped in the igraph crate. 

Is this something you'd be open to? 

Cheers,
Kevin

**Comment by mocsy** [comment]
Sorry, I haven't seen this for some reason. (10k unread mails)

Yeah I can try renaming or removing that package, as I never got realize my
vision for it.

**Comment by kvnvelasco** [comment]
Thanks! I've also moved on from this but might get around to it by the end of the year.
